### ISSUE TITLE
Interface to export Jupyter files to users' folder

### ISSUE THREAD

**Issue by duncancallaway** [NREL-SIIP/SIIPExamples.jl#30]
File permissions in 4_PowerSimulationsDynamics_examples set to read only, causing an error when attempting to write to log file.  Simple chmod fix, however would be nice if it worked out of the box.

I did not check other tutorials.

**Comment by jd-lara** [comment]
we are addressing this in #29. Thanks for the report

**Comment by jd-lara** [comment]
@duncancallaway how are you accessing the files? I can't reproduce the issue you are mentioning.

**Comment by duncancallaway** [comment]
I did an "add SIIPExamples" in the Julia REPL.  Then ran the code from a
Jupyter notebook, in Jupyter Lab, with Julia 1.6 kernel.

It appears that all .jl files in .julia/packages/ are read-only on my
machine for my regular user.  Perhaps others have their permissions set up
differently and so don't encounter this problem.

Ignorable problem if my permissions setup is idiosyncratic.  On the other
hand, one might put the .log files in a different directory that will
typically have full write access.

**Comment by jd-lara** [comment]
I see, yeah since the jupyter files are inside the package files they are read-only as per the Julia package manager. 

@claytonpbarrows we should allow users to export the jupyter notebooks to a local folder so that they can modify them. 

@duncancallaway thanks for reporting this.

**Comment by claytonpbarrows** [comment]
I've been thinking that we should remove the notebooks from the package altogether. It's a pain to have them as part of the repo because git can't really track changes. But it's nice to have the nbviewer and binder links to the most recent versions of the notebooks. Ideally, the right solution would:
1. store the notebooks as artifacts or in another repo
2. keep the notebooks synchronized with the repo
2. enable the creation/launch of notebooks from SIIPExamples (e.g. `notebook`)

**Comment by claytonpbarrows** [comment]
@kdheepak and @ptn111 FYI

**Comment by claytonpbarrows** [comment]
v0.1.7 should finally implement this request.
